// Static audio index, generated by scripts/export-bible-index.mjs from the
// live `BibleMem` / `config/BibleMem` Firestore collections (which are
// Admin-SDK-only — the client has no read rule for them, so this file is
// how the emergency page learns which verses have audio without a backend).
export interface VerseEntry {
  fileId: string;
  filename?: string;
}

export interface BookEntry {
  bookNum: number;
  bookName: string;
  chapters: Record<string, Record<string, VerseEntry>>;
}

export interface BibleMemIndex {
  generatedAt: string | null;
  books: Record<string, BookEntry>;
}

let cached: BibleMemIndex | null = null;

export async function loadBibleMemIndex(): Promise<BibleMemIndex> {
  if (cached) return cached;
  const res = await fetch(`${import.meta.env.BASE_URL}data/bibleMemIndex.json`);
  cached = (await res.json()) as BibleMemIndex;
  return cached;
}

export function sortedBooks(index: BibleMemIndex): BookEntry[] {
  return Object.values(index.books).sort((a, b) => a.bookNum - b.bookNum);
}

export function sortedChapters(book: BookEntry): string[] {
  return Object.keys(book.chapters).sort((a, b) => Number(a) - Number(b));
}

export function sortedVerses(book: BookEntry, chapter: string): string[] {
  return Object.keys(book.chapters[chapter] || {}).sort((a, b) => Number(a) - Number(b));
}

// Direct client -> Google Drive stream, no key/proxy needed since the
// folder is shared "Anyone with the link: Viewer".
export function driveAudioUrl(fileId: string): string {
  return `https://drive.google.com/uc?export=download&id=${fileId}`;
}
