// Static audio index, generated by scripts/export-bible-index.mjs by
// crawling the Bible MP3 Drive folder directly with an authenticated
// service account (the client has no such access, so this file is how the
// emergency page learns which verses exist and how to fetch them without a
// backend).
export interface VerseEntry {
  fileId: string;
  filename?: string;
  // Required for anonymous access to this specific file -- Drive requires a
  // resourcekey for public links to items shared before ~2021, and it is
  // per-file, not shared with the containing folder.
  resourceKey?: string;
}

export interface BookEntry {
  bookNum: number;
  bookName: string;
  chapters: Record<string, Record<string, VerseEntry>>;
}

export interface BibleMemIndex {
  generatedAt: string | null;
  books: Record<string, BookEntry>;
}

let cached: BibleMemIndex | null = null;

export async function loadBibleMemIndex(): Promise<BibleMemIndex> {
  if (cached) return cached;
  const res = await fetch(`${import.meta.env.BASE_URL}data/bibleMemIndex.json`);
  cached = (await res.json()) as BibleMemIndex;
  return cached;
}

export function sortedBooks(index: BibleMemIndex): BookEntry[] {
  return Object.values(index.books).sort((a, b) => a.bookNum - b.bookNum);
}

export function sortedChapters(book: BookEntry): string[] {
  return Object.keys(book.chapters).sort((a, b) => Number(a) - Number(b));
}

export function sortedVerses(book: BookEntry, chapter: string): string[] {
  return Object.keys(book.chapters[chapter] || {}).sort((a, b) => Number(a) - Number(b));
}

// Public, referrer-restricted key (Google Cloud Console -> APIs & Services
// -> Credentials), restricted to: API = Google Drive API only,
// Application = HTTP referrers -> https://praise.army/*. Injected at build
// time from the GOOGLE_DRIVE_API_KEY repo secret (see deploy.yml) so the
// raw value never appears in source/git -- even though it ends up in the
// shipped JS bundle either way (the restrictions are what make it safe to
// expose there, not keeping it out of the bundle, which isn't possible for
// a browser-facing key).
const DRIVE_API_KEY = import.meta.env.VITE_DRIVE_API_KEY;

// Fetches a verse's audio bytes and returns a local blob: URL for <audio
// src>. Can't just point <audio src> at Drive directly: the v3 API requires
// the resourcekey as a request header (X-Goog-Drive-Resource-Keys), and
// <audio src> has no way to send custom headers -- confirmed by testing the
// unofficial uc?export=download hotlink, which does NOT accept resourcekey
// as a query param despite that being Google's documented pattern for
// consumer share links. fetch() can set the header, and Drive's API sends
// proper CORS headers (verified: access-control-allow-origin scoped to our
// referrer-restricted key), so a plain client-side fetch + blob works with
// no server involved at all.
//
// The API key is passed via the X-Goog-Api-Key header, not a `key=` URL
// query param, even though Google supports both -- confirmed in production
// that some browser privacy/ad-blocking extensions strip `key=`-style query
// params as a generic tracking-parameter heuristic, which silently drops
// the key from the URL and gets a real 403 back from Google ("missing a
// valid API key") that arrives without CORS headers, showing up client-side
// as an opaque "blocked by CORS policy" error. The header form isn't a
// target for that class of URL-cleaning tool.
export async function fetchDriveAudioBlobUrl(entry: VerseEntry): Promise<string> {
  const headers: HeadersInit = { "X-Goog-Api-Key": DRIVE_API_KEY };
  if (entry.resourceKey) {
    headers["X-Goog-Drive-Resource-Keys"] = `${entry.fileId}/${entry.resourceKey}`;
  }
  const url = `https://www.googleapis.com/drive/v3/files/${entry.fileId}?alt=media`;
  const res = await fetch(url, { headers });
  if (!res.ok) {
    throw new Error(`Drive fetch failed: ${res.status} ${res.statusText}`);
  }
  const blob = await res.blob();
  return URL.createObjectURL(blob);
}
