// Static audio index, generated by scripts/export-bible-index.mjs by
// crawling the Bible MP3 Drive folder directly with an authenticated
// service account (the client has no such access, so this file is how the
// emergency page learns which verses exist and how to fetch them without a
// backend).
export interface VerseEntry {
  fileId: string;
  filename?: string;
  // Required for anonymous access to this specific file -- Drive requires a
  // resourcekey for public links to items shared before ~2021, and it is
  // per-file, not shared with the containing folder.
  resourceKey?: string;
}

export interface BookEntry {
  bookNum: number;
  bookName: string;
  chapters: Record<string, Record<string, VerseEntry>>;
}

export interface BibleMemIndex {
  generatedAt: string | null;
  books: Record<string, BookEntry>;
}

let cached: BibleMemIndex | null = null;

export async function loadBibleMemIndex(): Promise<BibleMemIndex> {
  if (cached) return cached;
  const res = await fetch(`${import.meta.env.BASE_URL}data/bibleMemIndex.json`);
  cached = (await res.json()) as BibleMemIndex;
  return cached;
}

export function sortedBooks(index: BibleMemIndex): BookEntry[] {
  return Object.values(index.books).sort((a, b) => a.bookNum - b.bookNum);
}

export function sortedChapters(book: BookEntry): string[] {
  return Object.keys(book.chapters).sort((a, b) => Number(a) - Number(b));
}

export function sortedVerses(book: BookEntry, chapter: string): string[] {
  return Object.keys(book.chapters[chapter] || {}).sort((a, b) => Number(a) - Number(b));
}

// Public, referrer-restricted key (Google Cloud Console -> APIs & Services
// -> Credentials), restricted to: API = Google Drive API only,
// Application = HTTP referrers -> https://praise.army/*. Injected at build
// time from the GOOGLE_DRIVE_API_KEY repo secret (see deploy.yml) so the
// raw value never appears in source/git -- even though it ends up in the
// shipped JS bundle either way (the restrictions are what make it safe to
// expose there, not keeping it out of the bundle, which isn't possible for
// a browser-facing key).
const DRIVE_API_KEY = import.meta.env.VITE_DRIVE_API_KEY;

// Fetches a verse's audio bytes and returns a local blob: URL for <audio
// src>. Can't just point <audio src> at Drive directly: the v3 API requires
// the resourcekey as a request header (X-Goog-Drive-Resource-Keys), and
// <audio src> has no way to send custom headers -- confirmed by testing the
// unofficial uc?export=download hotlink, which does NOT accept resourcekey
// as a query param despite that being Google's documented pattern for
// consumer share links. fetch() can set the header, and Drive's API sends
// proper CORS headers (verified: access-control-allow-origin scoped to our
// referrer-restricted key), so a plain client-side fetch + blob works with
// no server involved at all.
//
// The API key is passed via the X-Goog-Api-Key header, not a `key=` URL
// query param, even though Google supports both -- some browser privacy/
// ad-blocking extensions strip `key=`-style query params as a generic
// tracking-parameter heuristic. The header form isn't a target for that.
//
// referrerPolicy is set explicitly because the key is HTTP-referrer
// restricted (Google Cloud Console -> Application restrictions), and Google
// rejects a request with no referrer at all with a 403 that -- like the
// missing-key case -- arrives without CORS headers, so it shows up
// client-side as an opaque "blocked by CORS policy" error rather than a
// readable 403. Confirmed server-side: an empty referrer produces exactly
// that response; whatever suppresses the referrer in production (GitHub
// Pages' response headers, a browser privacy setting -- unconfirmed which)
// doesn't matter once it's forced here, since an explicit per-fetch
// referrerPolicy overrides page/platform defaults.
// Runs only when the main fetch below fails, to tell apart "Google is
// unreachable from this browser/network at all" from "specifically the
// custom-header, resourcekey-gated request is failing." Every attempt to
// reproduce a real-browser failure server-side -- matching key, matching
// referrer, matching per-file resourcekey, full Sec-Fetch-*/User-Agent
// headers, even the CORS preflight OPTIONS itself -- has succeeded via
// curl, which means the remaining suspects are things a data-center curl
// process can't see: a TLS-inspecting corporate/ISP proxy, antivirus HTTPS
// scanning, or DNS-level filtering on the *user's* path to Google that
// mangles CORS response headers. This probe is a plain GET with no custom
// headers at all (key as a `key=` query param instead), so the browser
// never issues a CORS preflight for it -- if this also fails, the block is
// happening before headers or resourcekeys even come into play.
async function probeDriveReachability(): Promise<string> {
  try {
    const res = await fetch(`https://www.googleapis.com/drive/v3/about?fields=kind&key=${DRIVE_API_KEY}`);
    const cors = res.headers.get("access-control-allow-origin") ?? "(none)";
    return `probe: HTTP ${res.status}, access-control-allow-origin=${cors}`;
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err);
    return `probe: ALSO failed (${message}) -- Google is unreachable from this browser/network, not just the audio request`;
  }
}

export async function fetchDriveAudioBlobUrl(entry: VerseEntry): Promise<string> {
  const headers: HeadersInit = { "X-Goog-Api-Key": DRIVE_API_KEY };
  if (entry.resourceKey) {
    headers["X-Goog-Drive-Resource-Keys"] = `${entry.fileId}/${entry.resourceKey}`;
  }
  const url = `https://www.googleapis.com/drive/v3/files/${entry.fileId}?alt=media`;
  try {
    const res = await fetch(url, { headers, referrerPolicy: "origin" });
    if (!res.ok) {
      throw new Error(`Drive fetch failed: ${res.status} ${res.statusText}`);
    }
    const blob = await res.blob();
    return URL.createObjectURL(blob);
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err);
    const probe = await probeDriveReachability();
    throw new Error(`${message} | ${probe}`);
  }
}
